import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
const root = process.cwd();
const dist = resolve(root, "dist");
await rm(dist, { recursive: true, force: true });
await mkdir(resolve(dist, "server"), { recursive: true });
await mkdir(resolve(dist, "client"), { recursive: true });
await mkdir(resolve(dist, ".openai"), { recursive: true });
await cp(resolve(root, "out"), resolve(dist, "client"), { recursive: true });
await cp(resolve(root, "worker/index.js"), resolve(dist, "server/index.js"));
await cp(resolve(root, "worker/auth.js"), resolve(dist, "server/auth.js"));
await cp(resolve(root, "worker/signatures.js"), resolve(dist, "server/signatures.js"));
await cp(resolve(root, "worker/workflow-queue.js"), resolve(dist, "server/workflow-queue.js"));
await cp(resolve(root, "worker/golden-path.js"), resolve(dist, "server/golden-path.js"));
await writeFile(resolve(dist, "server/package.json"), '{"type":"module"}\n');
await cp(resolve(root, ".openai/hosting.json"), resolve(dist, ".openai/hosting.json"));
const worker = await readFile(resolve(dist, "server/index.js"), "utf8");
if (!worker.includes("export default") || !worker.includes("fetch(request")) throw new Error("Invalid Sites worker entrypoint");
await writeFile(resolve(dist, "BUILD_OK"), "RecoverHVAC Sites package\n");
console.log("Sites package ready: dist/server + dist/client");
